# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#permalink: /:year/:month/:day/:title.html   #博文的固定链接
#paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: robin li
  email: kuhan163@163.com
  link: https://robin163.github.io/ # Site settings

title: Robin blog
email: kuhan163@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robin163.github.io/" # the base hostname & protocol for your site
linkedin_username: robin163
github_username:  robin163

# Build settings
markdown: kramdown
#highlighter: pygments
